#!/bin/sh

test -n "$(which git-dpkg-mkquilt.awk)" \
  || export PATH=$PATH:${0%/*}

mktree_filter () (
  printf ".gitignore\n.gitattributes\n\ndebian\n" \
    | git-dpkg-mkquilt.awk -v ref="$1"
)

if test $# -lt 1; then
  echo "usage: $0 <upstream> [<diff-opts>...]"
  exit 1
fi

upstream="$1"; shift
export_tree=$(mktree_filter $upstream)
head_tree=$(mktree_filter HEAD)
mkdir -p debian/patches
git diff "$@" ${export_tree}..${head_tree} > debian/patches/git-patches.diff
echo "git-patches.diff" > debian/patches/series
